### PR TITLE
Very simple demo apps for Avro and JSON Schema

### PR DESCRIPTION
**Pull request by EricWittmann**

### CODE REVIEW

**Comment by alesj** [comment]
Already merged?

**Comment by EricWittmann** [comment]
Figured it was ok since I didn't touch any other parts of the demo.  Happy to make additional changes if you think it's necessary.

**Comment by alesj** [comment]
OK ...
Just wondering, since this was before we merged the actual PR ... 😉😋🙂

**Comment by EricWittmann** [comment]
Damn that's a good point.  Whoops!

**Pull request merged**
